language: php

php:
  - 5.5
  - 5.6

before_script:
  - composer require satooshi/php-coveralls:dev-master --prefer-source --no-interaction --dev

script: phpunit -c phpunit.xml --coverage-text

after_script:
  - php vendor/bin/coveralls -v
